linuxdeepin/dtkcommon

archlinux/PKGBUILD

remove pkgver function in PKGBUILD
Log:

fix: archlinux build failed

---

CMakeLists.txt

Tocmakefix

---

.reuse/dep5
CMakeLists.txt
LICENSES/BSD-3-Clause.txt
LICENSES/CC0-1.0.txt
README.md
cmake/Dtk/DtkConfig.cmake
cmake/Dtk/DtkInstallDConfigConfig.cmake
schemas/com.deepin.dtk.gschema.xml

将License从GPL-3.0-or-later更改为BSD-3-Clause
Log: 添加对应的license并且更新README.md

chore: update licenses and README.md

---

.reuse/dep5
README.zh_CN.md

docs: add README.zh_CN.md

---

LICENSES/BSD-3-Clause.txt

BSD-3-Clause time and owner add
Log: fix licence

fix(licence): licence

---

README.md

Correct README.
Log: Correct README

docs: Correct README

---

CMakeLists.txt
archlinux/PKGBUILD

原来的逻辑发现这边dtkcommon还没有改，想着把这个丑陋的逻辑扔掉

fix: mkspecs path

---

debian/control

chore: remove the conflix of dtkgui

---

CMakeLists.txt

fix: features install fix

---

debian/changelog

Log: update changelog
Influence: none

chore: update changelog update changelog

---

.reuse/dep5
linglong.yaml

add linglong.yaml to support linglong build
see https://linglong.dev/guide/ll-builder/manifests.html
Log: linglong
Influence: linglong
Change-Id: I32dbf4b1b3e6cfb1533b40970c2090a04665b348

feat: add linglong build support

---

linglong.yaml

This project uses DVERSION instead of VERSION.
Log: Fix extra variable passed for version

fix: extra variable passed for version

---

CMakeLists.txt

Use relative directory to support --prefix when install.
Log: optimize install directory

chore(cmake): optimize install directory

---

.reuse/dep5
CMakeLists.txt
cmake/DtkBuildHelper.cmake

dtk_gen_config_header: to generate dtk moudule config header file.
dtk_setup_code_coverage: check option EnableCov to turn on coverage test compile options
dtk_check_and_add_definitions: check and add compile definitions

feat(cmake): add cmake functions

---

misc/config.cmake.in

find_package(Dtk${DTK_VERSION_MAJOR} REQUIRED)
set(EnableCov CACHE BOOL OFF)
if (EnableCov)
dtk_setup_code_coverage(${LIB_NAME})
endif()

chore: include DtkBuildHelper.cmake

---

CMakeLists.txt

chore: move DtkBuildHelper to separate module

---

misc/config.cmake.in

see https://github.com/linuxdeepin/dtkcommon/pull/55

chore: not include DtkBuildHelper

---

archlinux/PKGBUILD

fix(build): archlinux build DTK_VERSION empty

---

cmake/DtkBuildHelper.cmake

chore: correct a typo in DtkBuildHelper.cmake

---

configs/org.deepin.dtk.preference.json

dconfig meta file for dtk logging rules

feat: install loggingrules meta files

---

configs/org.deepin.dtk.preference.json

`enableDtkAnimations` to enable/disable `dtk` animations default value is `false`
https://github.com/linuxdeepin/dtkgui/pull/263

chore: add enableDtkAnimations config

---

configs/org.deepin.dtk.preference.json

滚动条策略和紧凑模式现在通过dconfig来设置
pms: Task-365811

feat: add 'scrollBarPolicy' and 'sizeMode' config
